version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "php-task-definition"
        LoadBalancerInfo:
          ContainerName: "php-container"
          ContainerPort: 80

