version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - REPOSITORY_URI=054037124957.dkr.ecr.ap-south-1.amazonaws.com/php-project
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin $REPOSITORY_URI
      
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      
      - echo Fetching current task definition...
      - aws ecs describe-task-definition --task-definition php-task-definition --region ap-south-1 --query taskDefinition > taskdef.json
      
      - echo Updating task definition with new image...
      - |
        jq --arg IMAGE "$REPOSITORY_URI:$IMAGE_TAG" \
          '.containerDefinitions[0].image = $IMAGE |
           del(.taskDefinitionArn, .revision, .status, .requiresAttributes, .compatibilities, .registeredAt, .registeredBy)' \
          taskdef.json > taskdef-updated.json
      
      - echo Creating imageDetail.json for CodeDeploy...
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json
      
      - echo Build completed successfully

artifacts:
  files:
    - appspec.yaml
    - taskdef-updated.json
    - imageDetail.json